[package]
name = "smalands-rs"
version = "0.7.2"
authors = ["axel paulander <axel.paulander@gmail.com>"]
edition = "2021"

[features]
default = []
update = []

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
giftwrap = "0.3"
num-traits = "0.2"
serde_json = "1.0"
serde = "1.0"
serde_derive = "1.0"
chrono = "0.4"
dirs = "4.0"
iced_native = "0.5"
iced_pure = "0.2"
lazy_static = "1.4"
rusqlite_migration = "1.0"

[dependencies.self_update]
version = "0.27"
features = ["archive-zip", "archive-tar", "compression-flate2", "compression-zip-deflate", "compression-zip-bzip2"]

[dependencies.iced]
version = "0.4"
features = [
    # "glow", 
    "canvas", 
    "tokio", 
    "pure", 
    "image"
]

[dependencies.rusqlite]
version  = "0.26"
features = ["chrono", "bundled"]

[dependencies.iced_aw]
version = "0.2"
default-features = false
features = [
    "pure",
    "tab_bar", 
    "tabs", 
    "modal", 
    "card", 
    "number_input", 
    "date_picker",
    "badge",
    "colors"
]

[dependencies.genpdf]
version = "0.2"
features = ["images"]

[dependencies.indexmap]
version = "1.8"
features = ["serde-1"]

[dependencies.tokio]
version = "1.18"
features  = ["sync"]

# Metadata

[workspace.metadata.workspaces]
no_individual_tags = true
