[package]
name = "smalands-rs"
version = "0.5.3"
authors = ["axel paulander <axel.paulander@gmail.com>"]
edition = "2021"

[features]
default = []
update = []

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
giftwrap = "0.3.0"
num-traits = "0.2.14"
serde_json = "1.0.59"
serde = "1.0.117"
serde_derive = "1.0.117"
chrono = "0.4.19"
dirs = "4.0.0"
iced_native = "0.5.0"
iced_pure = "0.2.0"
lazy_static = "1.4.0"

[dependencies.self_update]
version = "0.27.0"
features = ["archive-zip", "archive-tar", "compression-flate2", "compression-zip-deflate", "compression-zip-bzip2"]

[dependencies.iced]
version = "0.4.2"
features = [
    # "glow", 
    "canvas", 
    "tokio", 
    "pure", 
    "image"
]

[dependencies.rusqlite]
version  = "0.26.3"
features = ["chrono", "bundled"]

[dependencies.iced_aw]
git = "https://github.com/iced-rs/iced_aw"
# tag = "v0.1.0"
rev = "045e16d"
default-features = false
features = ["tab_bar", "tabs", "modal", "card", "number_input", "date_picker"]

[dependencies.genpdf]
version = "0.2.0"
features = ["images"]

[dependencies.indexmap]
version = "1.8.1"
features = ["serde-1"]

[dependencies.tokio]
version = "1.18.2"
features  = ["sync"]

# Metadata

[workspace.metadata.workspaces]
no_individual_tags = true
