[package]
name = "smalands-rs"
version = "0.1.0"
authors = ["axel paulander <axel.paulander@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
giftwrap = "0.1.0"
iced = "0.3.0"
rusqlite = "0.25.3"
num-traits = "0.2.14"
serde_json = "1.0.59"

[dependencies.iced_aw]
git = "https://github.com/iced-rs/iced_aw"
branch = "main"
default-features = false
features = ["tab_bar", "tabs", "modal", "card", "number_input"]
