[package]
name = "smalands-rs"
version = "0.9.1"
authors = ["axel paulander <axel.paulander@gmail.com>"]
edition = "2021"

[features]
default = []
update = []

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
giftwrap = "0.5"
chrono = "0.4"
dirs = "4.0"
iced_native = "0.8"
iced_lazy = "0.4"
lazy_static = "1.4"
rusqlite_migration = "1.0"
futures = "0.3"

frost = {git = "https://github.com/Strosel/frost", tag="v0.4.0"}

[dependencies.self_update]
version = "0.27"
features = ["archive-zip", "archive-tar", "compression-flate2", "compression-zip-deflate", "compression-zip-bzip2"]

[dependencies.iced]
version = "0.7"
features = [
    # "glow", 
    "canvas", 
    "tokio", 
    "image"
]

[dependencies.rusqlite]
version  = "0.26"
features = ["chrono", "bundled"]

[dependencies.iced_aw]
git = "https://github.com/iced-rs/iced_aw"
tag = "v0.3.0"
default-features = false
features = [
    "tab_bar", 
    "tabs", 
    "modal", 
    "card", 
    "number_input", 
    "date_picker",
    "badge",
]

[dependencies.genpdf]
version = "0.2"
features = ["images"]

[dependencies.indexmap]
version = "1.8"
features = ["serde-1"]

[dependencies.tokio]
version = "1.18"
features  = ["sync"]

# Metadata

[workspace.metadata.workspaces]
no_individual_tags = true
