[package]
name = "smalands-rs"
version = "0.1.0"
authors = ["axel paulander <axel.paulander@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
giftwrap = "0.1.0"
iced = "0.3.0"
num-traits = "0.2.14"
serde_json = "1.0.59"
serde = "1.0.117"
serde_derive = "1.0.117"
chrono = "0.4.19"

[dependencies.rusqlite]
version  = "0.25.3"
features = ["chrono"]

[dependencies.iced_aw]
git = "https://github.com/iced-rs/iced_aw"
branch = "main"
default-features = false
features = ["tab_bar", "tabs", "modal", "card", "number_input"]

[dependencies.genpdf]
version = "0.2.0-alpha.1"
features = ["images"]

[dependencies.indexmap]
version = "1.6.2"
features = ["serde-1"]
