[package]
name = "smalands-rs"
version = "0.3.0"
authors = ["axel paulander <axel.paulander@gmail.com>"]
edition = "2021"

[features]
default = []
update = []

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
giftwrap = "0.3.0"
num-traits = "0.2.14"
serde_json = "1.0.59"
serde = "1.0.117"
serde_derive = "1.0.117"
chrono = "0.4.19"
dirs = "4.0.0"
self_update = "0.27.0"

[dependencies.iced]
version = "0.3.0"
features = [ "image"]

[dependencies.rusqlite]
version  = "0.26.1"
features = ["chrono", "bundled"]

[dependencies.iced_aw]
git = "https://github.com/iced-rs/iced_aw"
branch = "main"
default-features = false
features = ["tab_bar", "tabs", "modal", "card", "number_input"]

[dependencies.genpdf]
version = "0.2.0"
features = ["images"]

[dependencies.indexmap]
version = "1.7.0"
features = ["serde-1"]
