on:
  push:
    branches:
      - '**'
    tags-ignore:
      - v[0-9]+.*

jobs:
  cargo-test:
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - x86_64-apple-darwin
          - x86_64-pc-windows-gnu
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust
        run: rustup update stable
      - name: Install cross-compilation tools
        uses: taiki-e/setup-cross-toolchain-action@v1
        with:
          target: ${{ matrix.target }}
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            SMALANDS_PASSWORD: ${{ secrets.SMALANDS_PASSWORD }}
      - run: cargo test --release
