on:
  push:
    branches:
      - '**'
    tags-ignore:
      - v[0-9]+.*

jobs:
  cargo-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - x86_64-apple-darwin
          - x86_64-pc-windows-gnu
    steps:
      - uses: actions/checkout@v3
      - name: Install rustup
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SMALANDS_PASSWORD: ${{ secrets.SMALANDS_PASSWORD }}
      - run: cargo check --target=${{ matrix.target }}
      - run: cargo check --target=${{ matrix.target }} --release 
