on:
  push:
    branches:
      - '**'
    tags-ignore:
      - v[0-9]+.*

jobs:
  cargo-test:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: macos-latest
            target: x86_64-apple-darwin
          - os: windows-latest
            target: x86_64-pc-windows-gnu
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Install rustup
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
      - run: cargo check --target=${{ matrix.target }}
      - run: cargo check --target=${{ matrix.target }} --release 
        env:
          SMALANDS_PASSWORD: ${{ secrets.SMALANDS_PASSWORD }}
